spring:
 application:
  name: service-registry
 cloud:
  config:
   uri: http://localhost:8888
  
server:
 port: 8761
 
eureka:
 instance:
  hostname: localhost
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
 server:
  enable-self-preservation: true  
 
 
---
 # For deployment in Docker containers
spring:
  profiles: docker
  cloud:
   config:
    uri: http://config-server:8888