# Eureka
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
  enabled: true
 instance:
  preferIpAddress: true

spring:
# Zipkin
 zipkin:
  baseUrl: http://localhost:9411/
  sender:
   type: web
 sleuth:
  sampler:
   probability: 1
# RabbitMQ
 rabbitmq:
  host: localhost
  port: 5672
